services:
  zmsp:
    container_name: zmsp
    hostname: zmsp
    restart: unless-stopped
    network_mode: bridge
    mem_limit: 128m
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - 6638:6638
